name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Step 3: Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Step 4: Build & run tests
      - name: Build and Test
        run: |
          ./gradlew clean
          ./gradlew build
          # Run unit test
          ./gradlew test
          # ./gradlew connectedCheck
          
      - name: Run Unit Tests & Coverage
        run: |
           ./gradlew clean testDebugUnitTest jacocoTestReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: app/build/reports/jacoco/jacocoTestReport/html

      # Step 5: 启动 Android Emulator 并执行仪表/集成测试
      - name: Run instrumented tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30            # 指定 Emulator 的 API Level (常见 29/30/31 等)
          script: ./gradlew connectedDebugAndroidTest
          target: google_apis      # 或者 google_apis_playstore
          arch: x86_64
          profile: default
          # 你也可以使用 'system-images;android-30;google_apis;x86_64' 作为 customPackage，如果默认镜像无法正常安装
          customPackage: 'sys-img-x86_64-google_apis-30'
          emulator-options: -no-snapshot

